version: '3'

services:

  nginx:
    image: nginx:latest
    ports:
      - ${EXTERNAL_NGINX_PORT:-8000}:80
    volumes:
      - ./public:/code/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    image: laravel-react-docker-chat-app/php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/code:cached

  node:
    image: laravel-react-docker-chat-app/node
    build:
      context: .
      dockerfile: docker/node/Dockerfile

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: laravel

  redis:
    image: redis:latest
